from django.urls import path
from .views import (
    OrderCreateView, OrderListView, AdminOrderListView, OrderStatusUpdateView,
    OrderItemDeleteView, OrderCancelView, OrderValidateView, OrdersOpenedTodayView, OrdersClosedTodayView,
    DailyRevenueView, GlobalDailyRevenueView, ServeurPerformanceView,
    CaissierDailySummaryView, DepartmentProfitabilityReportView, GlobalCashPositionView,
    CashExpenseListCreateView, CashExpenseDetailView, TransactionListView,
    ConsignmentCreateView, ConsignmentListView, ConsignmentReturnView,
    ClientTabCreateView, ClientTabListView, ClientTabDetailView, ClientTabAddItemsView,
    ClientTabInvoiceView, ClientTabInvoicePdfView, ClientTabCloseView, BonCancelView, BonValidateView
)

urlpatterns = [
    path('', OrderListView.as_view(), name='order-list'),
    path('all/', AdminOrderListView.as_view(), name='admin-order-list'),
    path('create/', OrderCreateView.as_view(), name='order-create'),
    path('<uuid:pk>/update/', OrderStatusUpdateView.as_view(), name='order-update'),
    path('<uuid:order_id>/items/<int:item_id>/', OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('<uuid:order_id>/cancel/', OrderCancelView.as_view(), name='order-cancel'),
    path('<uuid:pk>/validate/', OrderValidateView.as_view(), name='order-validate'),
    path('opened/', OrdersOpenedTodayView.as_view(), name='orders-opened'),
    path('closed/', OrdersClosedTodayView.as_view(), name='orders-closed'),
    path('server/revenue/', DailyRevenueView.as_view(), name='orders-daily-revenue'),
    path('global/revenue/', GlobalDailyRevenueView.as_view(), name='global-daily-revenue'),
    path('caissier/summary/', CaissierDailySummaryView.as_view(), name='caissier-daily-summary'),
    path('orders/performance/serveurs/', ServeurPerformanceView.as_view(), name='serveur-performance'),
    path('reports/profitability/', DepartmentProfitabilityReportView.as_view(), name='profitability-report'),
    path('reports/cash-position/', GlobalCashPositionView.as_view(), name='cash-position-report'),
    path('cash-expenses/', CashExpenseListCreateView.as_view(), name='cash-expense-list-create'),
    path('cash-expenses/<uuid:pk>/', CashExpenseDetailView.as_view(), name='cash-expense-detail'),
    path('transactions/', TransactionListView.as_view(), name='transaction-list'),
    path('consignments/', ConsignmentListView.as_view(), name='consignment-list'),
    path('consignments/create/', ConsignmentCreateView.as_view(), name='consignment-create'),
    path('consignments/<uuid:pk>/return/', ConsignmentReturnView.as_view(), name='consignment-return'),
    path('client-tabs/create/', ClientTabCreateView.as_view(), name='client-tab-create'),
    path('client-tabs/', ClientTabListView.as_view(), name='client-tab-list'),
    path('client-tabs/<uuid:pk>/', ClientTabDetailView.as_view(), name='client-tab-detail'),
    path('client-tabs/<uuid:pk>/items/', ClientTabAddItemsView.as_view(), name='client-tab-add-items'),
    path('client-tabs/<uuid:pk>/invoice/', ClientTabInvoiceView.as_view(), name='client-tab-invoice'),
    path('client-tabs/<uuid:pk>/invoice-pdf/', ClientTabInvoicePdfView.as_view(), name='client-tab-invoice-pdf'),
    path('client-tabs/<uuid:pk>/encaisser/', ClientTabCloseView.as_view(), name='client-tab-close'),
    path('bons/<uuid:pk>/cancel/', BonCancelView.as_view(), name='bon-cancel'),
    path('bons/<uuid:pk>/validate/', BonValidateView.as_view(), name='bon-validate'),
]
