# Generated by Django 6.0.7 on 2026-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_department'),
        ('users', '0003_alter_user_last_login_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_transfer_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='organisations.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('approvisionneur', 'Approvisionneur'), ('caissier', 'Caissier'), ('barman', 'Barman'), ('serveur', 'Serveur')], max_length=20),
        ),
    ]
