# Generated by Django 6.0.7 on 2026-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_barman_to_caissier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('approvisionneur', 'Approvisionneur'), ('caissier', 'Caissier'), ('serveur', 'Serveur')], max_length=20),
        ),
    ]
