# Generated by Django 6.0.7 on 2026-07-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Peut gérer les utilisateurs'), ('manage_user_permissions', 'Peut modifier les droits des utilisateurs')]},
        ),
    ]
