# Generated by Django 6.0.7 on 2026-07-30 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_cashier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'caissier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_serveurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
