# Generated by Django 6.0.7 on 2026-08-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_assigned_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
