# Generated by Django 6.0.7 on 2026-09-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_must_change_password_and_reset_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Peut g?rer les utilisateurs'), ('manage_user_permissions', 'Peut modifier les droits des utilisateurs')]},
        ),
    ]
