# Generated by Django 6.0.7 on 2026-08-20 10:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0010_organisation_archivee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('duree_jours', models.PositiveIntegerField()),
                ('montant_xaf', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empreinte', models.CharField(db_index=True, max_length=64, unique=True)),
                ('numero_serie', models.CharField(db_index=True, max_length=40, unique=True)),
                ('duree_jours', models.PositiveIntegerField()),
                ('emis_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_le', models.DateTimeField()),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('utilise', 'Utilisé'), ('expire', 'Expiré'), ('revoque', 'Révoqué')], default='actif', max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_activation', to='organisations.organisation')),
                ('emis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_emis', to='console.editeur')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes_activation', to='console.formule')),
            ],
        ),
        migrations.CreateModel(
            name='EditeurToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('editeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='console.editeur')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_expiration', models.DateTimeField()),
                ('montant_xaf', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('expire', 'Expiré'), ('remplace', 'Remplacé')], default='en_cours', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='organisations.organisation')),
                ('ouvert_par_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_ouverts', to='console.codeactivation')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='console.formule')),
            ],
            options={
                'ordering': ['-date_expiration'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('fait_le', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='console.editeur')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-fait_le'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_xaf', models.PositiveIntegerField()),
                ('operateur', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('especes', 'Espèces')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('recu_le', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='organisations.organisation')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_saisis', to='console.editeur')),
            ],
            options={
                'ordering': ['-recu_le'],
            },
        ),
    ]
