--
-- PostgreSQL database dump
--

\restrict ytnqL6RNX1irc8U8ZlZoTfHpdiN8Bd1FxBUyhJc246EI2OxrJeWSm8hoi0QrFkH

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: order_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.order_status AS ENUM (
    'ouverte',
    'servie',
    'fermee'
);


ALTER TYPE public.order_status OWNER TO postgres;

--
-- Name: payment_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.payment_type AS ENUM (
    'cash',
    'mobile_money'
);


ALTER TYPE public.payment_type OWNER TO postgres;

--
-- Name: replenishment_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.replenishment_status AS ENUM (
    'en_attente',
    'approuve',
    'rejete'
);


ALTER TYPE public.replenishment_status OWNER TO postgres;

--
-- Name: stock_request_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.stock_request_status AS ENUM (
    'pending',
    'approved',
    'rejected'
);


ALTER TYPE public.stock_request_status OWNER TO postgres;

--
-- Name: subscription_plan; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.subscription_plan AS ENUM (
    'free',
    'pro',
    'premium'
);


ALTER TYPE public.subscription_plan OWNER TO postgres;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'superadmin',
    'admin',
    'barman',
    'serveur'
);


ALTER TYPE public.user_role OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    description text
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    CONSTRAINT order_items_quantity_check CHECK ((quantity > 0)),
    CONSTRAINT order_items_unit_price_check CHECK ((unit_price >= (0)::numeric))
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid NOT NULL,
    serveur_id uuid,
    number_of_customers integer NOT NULL,
    status public.order_status DEFAULT 'ouverte'::public.order_status NOT NULL,
    total_amount numeric(10,2) DEFAULT 0 NOT NULL,
    payment_type public.payment_type,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone,
    CONSTRAINT orders_number_of_customers_check CHECK ((number_of_customers > 0)),
    CONSTRAINT orders_total_amount_check CHECK ((total_amount >= (0)::numeric))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: TABLE orders; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.orders IS 'Commandes clients associÃ©es Ã  un serveur et Ã  une organisation';


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id uuid NOT NULL,
    number_of_customers integer NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    payment_type character varying(20),
    created_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    organisation_id uuid NOT NULL,
    serveur_id uuid
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    order_id uuid NOT NULL,
    product_id uuid NOT NULL
);


ALTER TABLE public.orders_orderitem OWNER TO postgres;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_replenishmentitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_replenishmentitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    product_id uuid NOT NULL,
    request_id uuid NOT NULL
);


ALTER TABLE public.orders_replenishmentitem OWNER TO postgres;

--
-- Name: orders_replenishmentitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_replenishmentitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_replenishmentitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_replenishmentrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_replenishmentrequest (
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    approved_at timestamp with time zone,
    barman_id uuid,
    organisation_id uuid NOT NULL
);


ALTER TABLE public.orders_replenishmentrequest OWNER TO postgres;

--
-- Name: organisations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organisations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    address character varying(255),
    phone_contact character varying(20),
    subscription_plan public.subscription_plan DEFAULT 'free'::public.subscription_plan NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.organisations OWNER TO postgres;

--
-- Name: TABLE organisations; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.organisations IS 'EntitÃ© de base du SaaS : chaque organisation reprÃ©sente un bar ou une structure cliente';


--
-- Name: organisations_organisation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organisations_organisation (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    address character varying(255),
    phone_contact character varying(20),
    subscription_plan character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    description text,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.organisations_organisation OWNER TO postgres;

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid NOT NULL,
    category_id uuid,
    name character varying(100) NOT NULL,
    description text,
    price numeric(10,2) NOT NULL,
    image_url text,
    stock_quantity integer DEFAULT 0 NOT NULL,
    min_threshold integer DEFAULT 5 NOT NULL,
    unit character varying(20) DEFAULT 'piÃ¨ce'::character varying NOT NULL,
    CONSTRAINT products_min_threshold_check CHECK ((min_threshold >= 0)),
    CONSTRAINT products_price_check CHECK ((price >= (0)::numeric)),
    CONSTRAINT products_stock_quantity_check CHECK ((stock_quantity >= 0))
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: TABLE products; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.products IS 'Produits vendus et gÃ©rÃ©s par organisation';


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_category (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    organisation_id uuid NOT NULL
);


ALTER TABLE public.products_category OWNER TO postgres;

--
-- Name: products_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_product (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    price numeric(10,2) NOT NULL,
    image_url text,
    stock_quantity integer NOT NULL,
    category_id uuid,
    organisation_id uuid NOT NULL,
    min_threshold integer NOT NULL,
    unit character varying(20) NOT NULL,
    CONSTRAINT products_product_min_threshold_check CHECK ((min_threshold >= 0))
);


ALTER TABLE public.products_product OWNER TO postgres;

--
-- Name: products_stockrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_stockrequest (
    id uuid NOT NULL,
    requested_quantity integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    requested_by character varying(100) NOT NULL,
    organisation_id uuid NOT NULL,
    product_id uuid NOT NULL,
    CONSTRAINT products_stockrequest_requested_quantity_check CHECK ((requested_quantity >= 0))
);


ALTER TABLE public.products_stockrequest OWNER TO postgres;

--
-- Name: replenishment_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.replenishment_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    request_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT replenishment_items_quantity_check CHECK ((quantity > 0))
);


ALTER TABLE public.replenishment_items OWNER TO postgres;

--
-- Name: replenishment_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.replenishment_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid NOT NULL,
    barman_id uuid,
    status public.replenishment_status DEFAULT 'en_attente'::public.replenishment_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    approved_at timestamp with time zone
);


ALTER TABLE public.replenishment_requests OWNER TO postgres;

--
-- Name: stock_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid NOT NULL,
    product_id uuid NOT NULL,
    requested_quantity integer NOT NULL,
    status public.stock_request_status DEFAULT 'pending'::public.stock_request_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    requested_by character varying(100) NOT NULL,
    CONSTRAINT stock_requests_requested_quantity_check CHECK ((requested_quantity > 0))
);


ALTER TABLE public.stock_requests OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid,
    name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    role public.user_role NOT NULL,
    password character varying(128) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_staff boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login timestamp with time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.users IS 'Utilisateurs du systÃ¨me avec rÃ´les multi-organisation';


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    organisation_id uuid
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vouchers_wifivoucher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vouchers_wifivoucher (
    id uuid NOT NULL,
    code character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id uuid NOT NULL,
    organisation_id uuid NOT NULL
);


ALTER TABLE public.vouchers_wifivoucher OWNER TO postgres;

--
-- Name: wifi_vouchers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wifi_vouchers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organisation_id uuid NOT NULL,
    order_id uuid NOT NULL,
    code character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.wifi_vouchers OWNER TO postgres;

--
-- Name: TABLE wifi_vouchers; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.wifi_vouchers IS 'Vouchers Wi-Fi gÃ©nÃ©rÃ©s pour des commandes';


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Token	6	add_token
22	Can change Token	6	change_token
23	Can delete Token	6	delete_token
24	Can view Token	6	view_token
25	Can add Token	7	add_tokenproxy
26	Can change Token	7	change_tokenproxy
27	Can delete Token	7	delete_tokenproxy
28	Can view Token	7	view_tokenproxy
29	Can add organisation	8	add_organisation
30	Can change organisation	8	change_organisation
31	Can delete organisation	8	delete_organisation
32	Can view organisation	8	view_organisation
33	Can add user	9	add_user
34	Can change user	9	change_user
35	Can delete user	9	delete_user
36	Can view user	9	view_user
37	Can add category	10	add_category
38	Can change category	10	change_category
39	Can delete category	10	delete_category
40	Can view category	10	view_category
41	Can add product	11	add_product
42	Can change product	11	change_product
43	Can delete product	11	delete_product
44	Can view product	11	view_product
45	Can add stock request	12	add_stockrequest
46	Can change stock request	12	change_stockrequest
47	Can delete stock request	12	delete_stockrequest
48	Can view stock request	12	view_stockrequest
49	Can add order item	14	add_orderitem
50	Can change order item	14	change_orderitem
51	Can delete order item	14	delete_orderitem
52	Can view order item	14	view_orderitem
53	Can add replenishment item	15	add_replenishmentitem
54	Can change replenishment item	15	change_replenishmentitem
55	Can delete replenishment item	15	delete_replenishmentitem
56	Can view replenishment item	15	view_replenishmentitem
57	Can add replenishment request	16	add_replenishmentrequest
58	Can change replenishment request	16	change_replenishmentrequest
59	Can delete replenishment request	16	delete_replenishmentrequest
60	Can view replenishment request	16	view_replenishmentrequest
61	Can add order	13	add_order
62	Can change order	13	change_order
63	Can delete order	13	delete_order
64	Can view order	13	view_order
65	Can add wifi voucher	17	add_wifivoucher
66	Can change wifi voucher	17	change_wifivoucher
67	Can delete wifi voucher	17	delete_wifivoucher
68	Can view wifi voucher	17	view_wifivoucher
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, organisation_id, name, description) FROM stdin;
aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa	11111111-1111-1111-1111-111111111111	Boissons	Boissons chaudes et froides
bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb	11111111-1111-1111-1111-111111111111	Plats	Plats principaux
cccccccc-cccc-cccc-cccc-cccccccccccc	22222222-2222-2222-2222-222222222222	Snacks	Petits d‚jeuners et snacks
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	authtoken	token
7	authtoken	tokenproxy
8	organisations	organisation
9	users	user
10	products	category
11	products	product
12	products	stockrequest
13	orders	order
14	orders	orderitem
15	orders	replenishmentitem
16	orders	replenishmentrequest
17	vouchers	wifivoucher
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	organisations	0001_initial	2026-07-25 23:04:13.720698+02
2	contenttypes	0001_initial	2026-07-25 23:04:13.737826+02
3	contenttypes	0002_remove_content_type_name	2026-07-25 23:04:13.751467+02
4	auth	0001_initial	2026-07-25 23:04:13.822531+02
5	auth	0002_alter_permission_name_max_length	2026-07-25 23:04:13.834126+02
6	auth	0003_alter_user_email_max_length	2026-07-25 23:04:13.842278+02
7	auth	0004_alter_user_username_opts	2026-07-25 23:04:13.854208+02
8	auth	0005_alter_user_last_login_null	2026-07-25 23:04:13.864883+02
9	auth	0006_require_contenttypes_0002	2026-07-25 23:04:13.867726+02
10	auth	0007_alter_validators_add_error_messages	2026-07-25 23:04:13.880839+02
11	auth	0008_alter_user_username_max_length	2026-07-25 23:04:13.890007+02
12	auth	0009_alter_user_last_name_max_length	2026-07-25 23:04:13.898686+02
13	auth	0010_alter_group_name_max_length	2026-07-25 23:04:13.914353+02
14	auth	0011_update_proxy_permissions	2026-07-25 23:04:13.925229+02
15	auth	0012_alter_user_first_name_max_length	2026-07-25 23:04:13.934103+02
16	users	0001_initial	2026-07-25 23:04:13.999571+02
17	admin	0001_initial	2026-07-25 23:04:14.028095+02
18	admin	0002_logentry_remove_auto_add	2026-07-25 23:04:14.050881+02
19	admin	0003_logentry_add_action_flag_choices	2026-07-25 23:04:14.0661+02
20	authtoken	0001_initial	2026-07-25 23:04:14.088469+02
21	authtoken	0002_auto_20160226_1747	2026-07-25 23:04:14.129957+02
22	authtoken	0003_tokenproxy	2026-07-25 23:04:14.133697+02
23	authtoken	0004_alter_tokenproxy_options	2026-07-25 23:04:14.139692+02
24	products	0001_initial	2026-07-25 23:04:14.192182+02
25	orders	0001_initial	2026-07-25 23:04:14.228771+02
26	orders	0002_initial	2026-07-25 23:04:14.409546+02
27	organisations	0002_rename_phone_organisation_phone_contact_and_more	2026-07-25 23:04:14.512491+02
28	products	0002_product_min_threshold_product_unit_stockrequest	2026-07-25 23:04:14.585788+02
29	sessions	0001_initial	2026-07-25 23:04:14.602809+02
30	users	0002_alter_user_organisation	2026-07-25 23:04:14.641541+02
31	users	0003_alter_user_last_login_alter_user_role	2026-07-25 23:04:14.674989+02
32	vouchers	0001_initial	2026-07-25 23:04:14.714181+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, order_id, product_id, quantity, unit_price) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, organisation_id, serveur_id, number_of_customers, status, total_amount, payment_type, created_at, closed_at) FROM stdin;
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, number_of_customers, status, total_amount, payment_type, created_at, closed_at, organisation_id, serveur_id) FROM stdin;
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderitem (id, quantity, unit_price, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: orders_replenishmentitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_replenishmentitem (id, quantity, product_id, request_id) FROM stdin;
\.


--
-- Data for Name: orders_replenishmentrequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_replenishmentrequest (id, status, created_at, approved_at, barman_id, organisation_id) FROM stdin;
\.


--
-- Data for Name: organisations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organisations (id, name, description, address, phone_contact, subscription_plan, created_at, updated_at) FROM stdin;
11111111-1111-1111-1111-111111111111	Bar Le Parrain	Bar principal du groupe	12 avenue de la Paix, Douala	+237690000001	premium	2026-07-24 18:27:32.409928+02	2026-07-24 18:27:32.409928+02
22222222-2222-2222-2222-222222222222	Snack Chez Jo	Snack rapide et restauration	45 rue des Cocotiers, Yaound‚	+237690000002	pro	2026-07-24 18:27:32.409928+02	2026-07-24 18:27:32.409928+02
\.


--
-- Data for Name: organisations_organisation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organisations_organisation (id, name, address, phone_contact, subscription_plan, created_at, description, updated_at) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, organisation_id, category_id, name, description, price, image_url, stock_quantity, min_threshold, unit) FROM stdin;
10101010-1010-1010-1010-101010101010	11111111-1111-1111-1111-111111111111	aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa	Coca Cola	Boisson gazeuse 33cl	1500.00	https://img/coca.png	20	5	bouteille
20202020-2020-2020-2020-202020202020	11111111-1111-1111-1111-111111111111	aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa	Jus de mangue	Jus frais	2000.00	https://img/jus.png	8	5	verre
30303030-3030-3030-3030-303030303030	11111111-1111-1111-1111-111111111111	bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb	Poulet brais‚	Plat sp‚cial du jour	5000.00	https://img/poulet.png	12	4	portion
40404040-4040-4040-4040-404040404040	22222222-2222-2222-2222-222222222222	cccccccc-cccc-cccc-cccc-cccccccccccc	Chips	Snack sal‚	1000.00	https://img/chips.png	15	5	sachet
\.


--
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_category (id, name, description, organisation_id) FROM stdin;
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_product (id, name, description, price, image_url, stock_quantity, category_id, organisation_id, min_threshold, unit) FROM stdin;
\.


--
-- Data for Name: products_stockrequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_stockrequest (id, requested_quantity, status, created_at, updated_at, requested_by, organisation_id, product_id) FROM stdin;
\.


--
-- Data for Name: replenishment_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.replenishment_items (id, request_id, product_id, quantity) FROM stdin;
80808080-8080-8080-8080-808080808080	70707070-7070-7070-7070-707070707070	20202020-2020-2020-2020-202020202020	10
90909090-9090-9090-9090-909090909090	70707070-7070-7070-7070-707070707070	30303030-3030-3030-3030-303030303030	5
\.


--
-- Data for Name: replenishment_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.replenishment_requests (id, organisation_id, barman_id, status, created_at, approved_at) FROM stdin;
70707070-7070-7070-7070-707070707070	11111111-1111-1111-1111-111111111111	55555555-5555-5555-5555-555555555555	approuve	2026-07-24 18:27:32.76535+02	\N
\.


--
-- Data for Name: stock_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stock_requests (id, organisation_id, product_id, requested_quantity, status, created_at, updated_at, requested_by) FROM stdin;
50505050-5050-5050-5050-505050505050	11111111-1111-1111-1111-111111111111	20202020-2020-2020-2020-202020202020	10	pending	2026-07-24 18:27:32.722992+02	2026-07-24 18:27:32.722992+02	Jean
60606060-6060-6060-6060-606060606060	11111111-1111-1111-1111-111111111111	30303030-3030-3030-3030-303030303030	5	approved	2026-07-24 18:27:32.722992+02	2026-07-24 18:27:32.722992+02	Jean
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, organisation_id, name, phone, role, password, is_active, is_staff, created_at, last_login) FROM stdin;
33333333-3333-3333-3333-333333333333	11111111-1111-1111-1111-111111111111	Moussa	+237690000010	superadmin	password123	t	t	2026-07-24 18:27:32.512539+02	\N
44444444-4444-4444-4444-444444444444	11111111-1111-1111-1111-111111111111	Aline	+237690000011	admin	password123	t	t	2026-07-24 18:27:32.512539+02	\N
55555555-5555-5555-5555-555555555555	11111111-1111-1111-1111-111111111111	Jean	+237690000012	barman	password123	t	f	2026-07-24 18:27:32.512539+02	\N
66666666-6666-6666-6666-666666666666	11111111-1111-1111-1111-111111111111	Prisca	+237690000013	serveur	password123	t	f	2026-07-24 18:27:32.512539+02	\N
77777777-7777-7777-7777-777777777777	22222222-2222-2222-2222-222222222222	Paul	+237690000014	admin	password123	t	t	2026-07-24 18:27:32.512539+02	\N
88888888-8888-8888-8888-888888888888	22222222-2222-2222-2222-222222222222	Doris	+237690000015	serveur	password123	t	f	2026-07-24 18:27:32.512539+02	\N
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user (password, last_login, is_superuser, id, name, phone, role, is_active, is_staff, created_at, organisation_id) FROM stdin;
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: vouchers_wifivoucher; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vouchers_wifivoucher (id, code, expires_at, created_at, order_id, organisation_id) FROM stdin;
\.


--
-- Data for Name: wifi_vouchers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wifi_vouchers (id, organisation_id, order_id, code, expires_at, created_at) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 1, false);


--
-- Name: orders_replenishmentitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_replenishmentitem_id_seq', 1, false);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: orders_replenishmentitem orders_replenishmentitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_replenishmentitem
    ADD CONSTRAINT orders_replenishmentitem_pkey PRIMARY KEY (id);


--
-- Name: orders_replenishmentrequest orders_replenishmentrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_replenishmentrequest
    ADD CONSTRAINT orders_replenishmentrequest_pkey PRIMARY KEY (id);


--
-- Name: organisations organisations_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisations
    ADD CONSTRAINT organisations_name_key UNIQUE (name);


--
-- Name: organisations_organisation organisations_organisation_name_260d90a1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisations_organisation
    ADD CONSTRAINT organisations_organisation_name_260d90a1_uniq UNIQUE (name);


--
-- Name: organisations_organisation organisations_organisation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisations_organisation
    ADD CONSTRAINT organisations_organisation_pkey PRIMARY KEY (id);


--
-- Name: organisations organisations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisations
    ADD CONSTRAINT organisations_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_stockrequest products_stockrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_stockrequest
    ADD CONSTRAINT products_stockrequest_pkey PRIMARY KEY (id);


--
-- Name: replenishment_items replenishment_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.replenishment_items
    ADD CONSTRAINT replenishment_items_pkey PRIMARY KEY (id);


--
-- Name: replenishment_requests replenishment_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.replenishment_requests
    ADD CONSTRAINT replenishment_requests_pkey PRIMARY KEY (id);


--
-- Name: stock_requests stock_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_requests
    ADD CONSTRAINT stock_requests_pkey PRIMARY KEY (id);


--
-- Name: users users_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_phone_key UNIQUE (phone);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_phone_key UNIQUE (phone);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: vouchers_wifivoucher vouchers_wifivoucher_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers_wifivoucher
    ADD CONSTRAINT vouchers_wifivoucher_code_key UNIQUE (code);


--
-- Name: vouchers_wifivoucher vouchers_wifivoucher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers_wifivoucher
    ADD CONSTRAINT vouchers_wifivoucher_pkey PRIMARY KEY (id);


--
-- Name: wifi_vouchers wifi_vouchers_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wifi_vouchers
    ADD CONSTRAINT wifi_vouchers_code_key UNIQUE (code);


--
-- Name: wifi_vouchers wifi_vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wifi_vouchers
    ADD CONSTRAINT wifi_vouchers_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_categories_organisation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_categories_organisation_id ON public.categories USING btree (organisation_id);


--
-- Name: idx_order_items_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);


--
-- Name: idx_orders_organisation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orders_organisation_id ON public.orders USING btree (organisation_id);


--
-- Name: idx_orders_serveur_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orders_serveur_id ON public.orders USING btree (serveur_id);


--
-- Name: idx_orders_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orders_status ON public.orders USING btree (status);


--
-- Name: idx_products_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_category_id ON public.products USING btree (category_id);


--
-- Name: idx_products_organisation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_organisation_id ON public.products USING btree (organisation_id);


--
-- Name: idx_replenishment_requests_barman_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_replenishment_requests_barman_id ON public.replenishment_requests USING btree (barman_id);


--
-- Name: idx_replenishment_requests_organisation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_replenishment_requests_organisation_id ON public.replenishment_requests USING btree (organisation_id);


--
-- Name: idx_stock_requests_organisation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_stock_requests_organisation_id ON public.stock_requests USING btree (organisation_id);


--
-- Name: idx_stock_requests_product_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_stock_requests_product_id ON public.stock_requests USING btree (product_id);


--
-- Name: idx_users_organisation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_organisation_id ON public.users USING btree (organisation_id);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: idx_wifi_vouchers_expires_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_wifi_vouchers_expires_at ON public.wifi_vouchers USING btree (expires_at);


--
-- Name: idx_wifi_vouchers_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_wifi_vouchers_order_id ON public.wifi_vouchers USING btree (order_id);


--
-- Name: orders_order_organisation_id_46ef4fe7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_organisation_id_46ef4fe7 ON public.orders_order USING btree (organisation_id);


--
-- Name: orders_order_serveur_id_5dc1c004; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_serveur_id_5dc1c004 ON public.orders_order USING btree (serveur_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: orders_replenishmentitem_product_id_2aba7610; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_replenishmentitem_product_id_2aba7610 ON public.orders_replenishmentitem USING btree (product_id);


--
-- Name: orders_replenishmentitem_request_id_f6456676; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_replenishmentitem_request_id_f6456676 ON public.orders_replenishmentitem USING btree (request_id);


--
-- Name: orders_replenishmentrequest_barman_id_8d0d9d81; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_replenishmentrequest_barman_id_8d0d9d81 ON public.orders_replenishmentrequest USING btree (barman_id);


--
-- Name: orders_replenishmentrequest_organisation_id_574d5981; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_replenishmentrequest_organisation_id_574d5981 ON public.orders_replenishmentrequest USING btree (organisation_id);


--
-- Name: organisations_organisation_name_260d90a1_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisations_organisation_name_260d90a1_like ON public.organisations_organisation USING btree (name varchar_pattern_ops);


--
-- Name: products_category_organisation_id_1f005301; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_category_organisation_id_1f005301 ON public.products_category USING btree (organisation_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_organisation_id_4acd6f16; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_organisation_id_4acd6f16 ON public.products_product USING btree (organisation_id);


--
-- Name: products_stockrequest_organisation_id_bf6bbfaf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_stockrequest_organisation_id_bf6bbfaf ON public.products_stockrequest USING btree (organisation_id);


--
-- Name: products_stockrequest_product_id_672493ac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_stockrequest_product_id_672493ac ON public.products_stockrequest USING btree (product_id);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_organisation_id_383db2a8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_organisation_id_383db2a8 ON public.users_user USING btree (organisation_id);


--
-- Name: users_user_phone_fe37f55c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_phone_fe37f55c_like ON public.users_user USING btree (phone varchar_pattern_ops);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: vouchers_wifivoucher_code_93499a48_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX vouchers_wifivoucher_code_93499a48_like ON public.vouchers_wifivoucher USING btree (code varchar_pattern_ops);


--
-- Name: vouchers_wifivoucher_order_id_97f5ea09; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX vouchers_wifivoucher_order_id_97f5ea09 ON public.vouchers_wifivoucher USING btree (order_id);


--
-- Name: vouchers_wifivoucher_organisation_id_819925e6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX vouchers_wifivoucher_organisation_id_819925e6 ON public.vouchers_wifivoucher USING btree (organisation_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: categories categories_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_items order_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: order_items order_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: orders_order orders_order_organisation_id_46ef4fe7_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_organisation_id_46ef4fe7_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_serveur_id_5dc1c004_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_serveur_id_5dc1c004_fk_users_user_id FOREIGN KEY (serveur_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders orders_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE;


--
-- Name: orders_replenishmentrequest orders_replenishment_organisation_id_574d5981_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_replenishmentrequest
    ADD CONSTRAINT orders_replenishment_organisation_id_574d5981_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_replenishmentitem orders_replenishment_product_id_2aba7610_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_replenishmentitem
    ADD CONSTRAINT orders_replenishment_product_id_2aba7610_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_replenishmentitem orders_replenishment_request_id_f6456676_fk_orders_re; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_replenishmentitem
    ADD CONSTRAINT orders_replenishment_request_id_f6456676_fk_orders_re FOREIGN KEY (request_id) REFERENCES public.orders_replenishmentrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_replenishmentrequest orders_replenishmentrequest_barman_id_8d0d9d81_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_replenishmentrequest
    ADD CONSTRAINT orders_replenishmentrequest_barman_id_8d0d9d81_fk_users_user_id FOREIGN KEY (barman_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders orders_serveur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_serveur_id_fkey FOREIGN KEY (serveur_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: products products_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;


--
-- Name: products_category products_category_organisation_id_1f005301_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_organisation_id_1f005301_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products products_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_category_id FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_organisation_id_4acd6f16_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_organisation_id_4acd6f16_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_stockrequest products_stockreques_organisation_id_bf6bbfaf_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_stockrequest
    ADD CONSTRAINT products_stockreques_organisation_id_bf6bbfaf_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_stockrequest products_stockreques_product_id_672493ac_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_stockrequest
    ADD CONSTRAINT products_stockreques_product_id_672493ac_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: replenishment_items replenishment_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.replenishment_items
    ADD CONSTRAINT replenishment_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: replenishment_items replenishment_items_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.replenishment_items
    ADD CONSTRAINT replenishment_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.replenishment_requests(id) ON DELETE CASCADE;


--
-- Name: replenishment_requests replenishment_requests_barman_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.replenishment_requests
    ADD CONSTRAINT replenishment_requests_barman_id_fkey FOREIGN KEY (barman_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: replenishment_requests replenishment_requests_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.replenishment_requests
    ADD CONSTRAINT replenishment_requests_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE;


--
-- Name: stock_requests stock_requests_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_requests
    ADD CONSTRAINT stock_requests_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE;


--
-- Name: stock_requests stock_requests_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_requests
    ADD CONSTRAINT stock_requests_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: users users_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE SET NULL;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_organisation_id_383db2a8_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_organisation_id_383db2a8_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vouchers_wifivoucher vouchers_wifivoucher_order_id_97f5ea09_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers_wifivoucher
    ADD CONSTRAINT vouchers_wifivoucher_order_id_97f5ea09_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vouchers_wifivoucher vouchers_wifivoucher_organisation_id_819925e6_fk_organisat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers_wifivoucher
    ADD CONSTRAINT vouchers_wifivoucher_organisation_id_819925e6_fk_organisat FOREIGN KEY (organisation_id) REFERENCES public.organisations_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wifi_vouchers wifi_vouchers_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wifi_vouchers
    ADD CONSTRAINT wifi_vouchers_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: wifi_vouchers wifi_vouchers_organisation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wifi_vouchers
    ADD CONSTRAINT wifi_vouchers_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict ytnqL6RNX1irc8U8ZlZoTfHpdiN8Bd1FxBUyhJc246EI2OxrJeWSm8hoi0QrFkH

