# Generated by Django 6.0.7 on 2026-09-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_cashierdaybalance_adjusted_after_close_at'),
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUpstreamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('body', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('client_created_at', models.CharField(blank=True, max_length=64)),
                ('cashier_session', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'En attente de remontee'), ('quarantined', 'En echec definitif')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_upstream_requests', to='organisations.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_upstream_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['organisation', 'status', 'id'], name='upstream_pending_idx')],
            },
        ),
    ]
