# Generated by Django 6.0.7 on 2026-09-21 20:46

import django.db.models.deletion
import sync.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_cashierdaybalance_adjusted_after_close_at'),
        ('sync', '0002_pendingupstreamrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('token', models.CharField(default=sync.models.generate_instance_token, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_instances', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation__name', 'name'],
            },
        ),
    ]
