# Generated by Django 6.0.7 on 2026-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_syncinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncinstance',
            name='pending_operations',
            field=models.IntegerField(default=0),
        ),
    ]
