# Generated by Django 6.0.7 on 2026-09-22 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_cashierdaybalance_adjusted_after_close_at'),
        ('sync', '0004_syncinstance_pending_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncinstance',
            name='last_downstream_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PendingDownstreamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_downstream_requests', to='organisations.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_downstream_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['organisation', 'id'], name='downstream_pending_idx')],
            },
        ),
    ]
