# Generated by Django 6.0.7 on 2026-09-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_cashierdaybalance_adjusted_after_close_at'),
        ('sync', '0005_syncinstance_last_downstream_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAbandonnee',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_created_at', models.CharField(blank=True, max_length=64)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('signalee_le', models.DateTimeField(auto_now_add=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_abandonnees', to='organisations.organisation')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_abandonnees_traitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_abandonnees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signalee_le'],
                'indexes': [models.Index(fields=['organisation', 'traitee_le'], name='abandon_org_traitee_idx')],
            },
        ),
    ]
