"""
Django settings for le_parrain project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)


# ALLOWED_HOSTS / CORS / CSRF : liste de base (dev local + tunnels ngrok) toujours presente,
# complete par des valeurs lues dans .env (EXTRA_ALLOWED_HOSTS / EXTRA_CORS_ORIGINS /
# EXTRA_CSRF_ORIGINS, listes separees par des virgules) - permet d'ajouter le domaine de prod
# (LWS) et l'URL Vercel du frontend sans jamais modifier ce fichier par environnement.
def _split_env_list(value):
    return [item.strip() for item in value.split(',') if item.strip()]

# IP LAN du poste de dev, necessaire pour que l'app mobile (tablette physique,
# le_parrain_mobile/.env.development) puisse atteindre ce backend en dev.
# Attention : cette IP change si le reseau Wi-Fi change (DHCP) - verifier avec `ipconfig`.
# .ngrok-free.app (wildcard) : le reseau local de la tablette de test bloque les connexions
# directes entre appareils (isolation Wi-Fi/routeur non resolue) - on tunnelise via ngrok en
# attendant. L'URL ngrok change a chaque redemarrage du tunnel (plan gratuit) ; le wildcard
# evite d'avoir a modifier ce fichier a chaque fois.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.1.156", ".ngrok-free.app"] + _split_env_list(
    config('EXTRA_ALLOWED_HOSTS', default='')
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
] + _split_env_list(config('EXTRA_CORS_ORIGINS', default=''))

# When the browser sends an Origin header on cross-origin POSTs, Django will
# validate it against this list. Include the frontend origin (with scheme).
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "http://localhost:4200",
    "http://127.0.0.1:4200",
] + _split_env_list(config('EXTRA_CSRF_ORIGINS', default=''))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'organisations',
    'users',
    'products',
    'orders',
    'vouchers',
    'console',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'console.middleware.LicenceGateMiddleware',
    'organisations.middleware.BusinessDayGateMiddleware',
]

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'le_parrain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'le_parrain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Signature des codes d'activation (console systeme) - voir console/management/commands/generer_cle_editeur.py.
# Cle privee : secret, uniquement dans .env, lue par console/services/licence.py (emission).
# Cle publique : pas un secret, lue par organisations/services/verification_licence.py (verification).
EDITEUR_ED25519_PRIVATE_KEY_B64 = config('EDITEUR_ED25519_PRIVATE_KEY_B64', default='')
EDITEUR_ED25519_PUBLIC_KEY_B64 = config('EDITEUR_ED25519_PUBLIC_KEY_B64', default='')

# Affichees telles quelles sur l'ecran supadmin "Abonnement" (organisations/views.py::OrganisationAbonnementView)
EDITEUR_COORDONNEES_PAIEMENT = {
    'Mobile Money': config('EDITEUR_MOBILE_MONEY_NUMERO', default=''),
    'Orange Money': config('EDITEUR_ORANGE_MONEY_NUMERO', default=''),
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Requis par `collectstatic` (sert le CSS/JS de l'admin Django et de la vue navigable DRF en
# production - en dev ils sont servis directement depuis les apps, STATIC_ROOT n'intervient pas).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (product images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
