"""
Django settings for le_parrain project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)


# ALLOWED_HOSTS / CORS / CSRF : liste de base (dev local + tunnels ngrok) toujours presente,
# complete par des valeurs lues dans .env (EXTRA_ALLOWED_HOSTS / EXTRA_CORS_ORIGINS /
# EXTRA_CSRF_ORIGINS, listes separees par des virgules) - permet d'ajouter le domaine de prod
# (LWS) et l'URL Vercel du frontend sans jamais modifier ce fichier par environnement.
def _split_env_list(value):
    return [item.strip() for item in value.split(',') if item.strip()]

# IP LAN du poste de dev, necessaire pour que l'app mobile (tablette physique,
# le_parrain_mobile/.env.development) puisse atteindre ce backend en dev.
# Attention : cette IP change si le reseau Wi-Fi change (DHCP) - verifier avec `ipconfig`.
# .ngrok-free.app (wildcard) : le reseau local de la tablette de test bloque les connexions
# directes entre appareils (isolation Wi-Fi/routeur non resolue) - on tunnelise via ngrok en
# attendant. L'URL ngrok change a chaque redemarrage du tunnel (plan gratuit) ; le wildcard
# evite d'avoir a modifier ce fichier a chaque fois.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.1.156", ".ngrok-free.app"] + _split_env_list(
    config('EXTRA_ALLOWED_HOSTS', default='')
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
] + _split_env_list(config('EXTRA_CORS_ORIGINS', default=''))

# When the browser sends an Origin header on cross-origin POSTs, Django will
# validate it against this list. Include the frontend origin (with scheme).
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "http://localhost:4200",
    "http://127.0.0.1:4200",
] + _split_env_list(config('EXTRA_CSRF_ORIGINS', default=''))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'organisations',
    'users',
    'products',
    'orders',
    'vouchers',
    'console',
    'sync',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'console.middleware.LicenceGateMiddleware',
    'organisations.middleware.BusinessDayGateMiddleware',
    # En dernier, donc au plus pres des vues : une requete refusee par les gardes ci-dessus
    # n'arrive jamais jusqu'ici et n'a pas a etre remontee. Sans effet sur le serveur central
    # (voir sync/upstream.py).
    'sync.upstream.UpstreamCaptureMiddleware',
    # Symetrique du precedent, et sans effet sur une instance locale : capture les corrections
    # que l'admin fait a distance, pour qu'elles redescendent vers le bar (voir
    # sync/downstream.py).
    'sync.downstream.DownstreamCaptureMiddleware',
]

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'le_parrain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'le_parrain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        # Remontee des operations depuis une instance installee dans un bar. Placee apres
        # l'authentification par jeton : elle ne s'active que sur un entete 'Instance', et
        # laisse passer tout le reste (voir sync/authentication.py).
        'sync.authentication.SyncInstanceAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Ajoute un code machine a chaque erreur, pour que la file d'attente hors-ligne puisse
    # decider seule entre reessayer, abandonner ou alerter (voir sync/exceptions.py).
    'EXCEPTION_HANDLER': 'sync.exceptions.exception_handler',
}

# Role de cette instance : 'cloud' (serveur central, admin et approvisionneur) ou 'local'
# (instance installee sur le poste du caissier, dans le bar).
#
# Le bar doit pouvoir travailler sans internet : une instance locale autorise donc des actions
# que le cloud reserve a l'admin - ouvrir la journee, par exemple, sans quoi une coupure le matin
# empecherait le bar d'ouvrir. A l'inverse, le cloud refuse certaines actions sur des donnees
# qu'un bar hors-ligne est peut-etre en train de modifier, faute de quoi les deux versions
# divergeraient sans moyen de les reconcilier.
INSTANCE_ROLE = config('INSTANCE_ROLE', default='cloud')
IS_LOCAL_INSTANCE = INSTANCE_ROLE == 'local'

# Coordonnees du serveur central, utilisees par une instance locale pour y remonter ses
# operations (voir sync/management/commands/push_upstream.py). Sans objet sur le cloud.
CLOUD_API_URL = config('CLOUD_API_URL', default='')
INSTANCE_TOKEN = config('INSTANCE_TOKEN', default='')

# Adresse a laquelle l'instance se joint elle-meme pour appliquer les corrections descendues du
# serveur central (voir sync/management/commands/pull_operations.py). Elle repasse par sa propre
# API plutot que d'ecrire en base : une annulation doit rejouer la meme logique metier - stock
# rendu, ecritures au journal, session de caisse - que si le caissier l'avait faite sur place.
LOCAL_API_URL = config('LOCAL_API_URL', default='http://127.0.0.1:8000')

# Interface du caissier, servie par l'instance du bar elle-meme (voir le_parrain/spa.py).
# Un bar a plusieurs caisses : toutes doivent joindre le meme serveur, donc la page ne peut pas
# contenir une adresse figee sur localhost. Sans objet sur le serveur central.
INSTANCE_SPA_DIR = config(
    'INSTANCE_SPA_DIR',
    default=str(BASE_DIR.parent / 'le_parrain_front-main' / 'dist' / 'esther-pay' / 'browser'),
)

# Signature des codes d'activation (console systeme) - voir console/management/commands/generer_cle_editeur.py.
# Cle privee : secret, uniquement dans .env, lue par console/services/licence.py (emission).
# Cle publique : pas un secret, lue par organisations/services/verification_licence.py (verification).
EDITEUR_ED25519_PRIVATE_KEY_B64 = config('EDITEUR_ED25519_PRIVATE_KEY_B64', default='')
EDITEUR_ED25519_PUBLIC_KEY_B64 = config('EDITEUR_ED25519_PUBLIC_KEY_B64', default='')

# Affichees telles quelles sur l'ecran supadmin "Abonnement" (organisations/views.py::OrganisationAbonnementView)
EDITEUR_COORDONNEES_PAIEMENT = {
    'Mobile Money': config('EDITEUR_MOBILE_MONEY_NUMERO', default=''),
    'Orange Money': config('EDITEUR_ORANGE_MONEY_NUMERO', default=''),
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Requis par `collectstatic` (sert le CSS/JS de l'admin Django et de la vue navigable DRF en
# production - en dev ils sont servis directement depuis les apps, STATIC_ROOT n'intervient pas).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (product images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sans ceci, Django masque les tracebacks des erreurs 500 PARTOUT en production (DEBUG=False) -
# y compris dans les logs serveur (docker logs, stdout du process), pas seulement dans la
# reponse HTTP renvoyee au client (masquage cote client volontaire, correct). Le handler
# 'mail_admins' par defaut de Django ne s'active que si ADMINS+email sont configures (jamais
# le cas ici) - sans handler 'console' explicite, une erreur 500 ne laisse absolument aucune
# trace visible nulle part. Log toujours vers stdout, avec la traceback complete.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
