# Generated by Django 6.0.7 on 2026-07-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_copy_department_family_values'),
        # products.0005 stops referencing organisations.DepartmentFamily (switches the
        # DepartmentStock/StockMovement.family FK to products.Category) — must run
        # before this migration deletes the model, or replaying migrations from
        # scratch fails to resolve the FK target.
        ('products', '0005_alter_departmentstock_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='family',
        ),
        migrations.DeleteModel(
            name='DepartmentFamily',
        ),
    ]
