# Generated by Django 6.0.7 on 2026-08-10 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_businessday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessday',
            name='opening_amount',
        ),
        migrations.CreateModel(
            name='CashierDayBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('business_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_balances', to='organisations.businessday')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business_day', 'cashier')},
            },
        ),
    ]
