# Generated by Django 6.0.7 on 2026-08-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_remove_businessday_opening_amount_cashierdaybalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessday',
            options={'ordering': ['-opened_at']},
        ),
    ]
