# Generated by Django 6.0.7 on 2026-08-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_alter_businessday_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='archivee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='derniere_activite_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('active', 'Active'), ('en_grace', 'En grâce'), ('bloquee', 'Bloquée'), ('suspendue', 'Suspendue')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='supadmin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_dirigee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
