# Generated by Django 6.0.7 on 2026-09-19 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_organisation_archivee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashierdaybalance',
            options={'ordering': ['opened_at']},
        ),
        migrations.AlterUniqueTogether(
            name='cashierdaybalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashierdaybalance',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashierdaybalance',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
