# Generated by Django 6.0.7 on 2026-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_alter_cashierdaybalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierdaybalance',
            name='adjusted_after_close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
