# Generated by Django 6.0.7 on 2026-07-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cashier_order_client_name_order_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replenishmentrequest',
            name='barman',
        ),
        migrations.RemoveField(
            model_name='replenishmentrequest',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='ReplenishmentItem',
        ),
        migrations.DeleteModel(
            name='ReplenishmentRequest',
        ),
    ]
