# Generated by Django 6.0.7 on 2026-07-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_replenishmentrequest_barman_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('view_global_revenue', "Peut voir le chiffre d'affaires global"), ('close_any_order', "Peut clôturer n'importe quelle commande, hors rattachement")]},
        ),
    ]
