# Generated by Django 6.0.7 on 2026-08-01 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cashexpense_deleted_at_cashexpense_deleted_by_and_more'),
        ('organisations', '0006_remove_department_family_delete_departmentfamily'),
        ('products', '0006_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('achat', 'Achat'), ('approvisionnement', 'Approvisionnement'), ('avoir', 'Avoir'), ('consignation', 'Consignation'), ('deconsignation', 'Deconsignation'), ('facturation', 'Facturation'), ('annulation_facture', 'Retour annulation de facture'), ('sortie_vente', 'Sortie vente'), ('transfert', 'Transfert'), ('sortie_caisse', 'Sortie de caisse'), ('avaries', 'Avaries')], max_length=40),
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('sortie', 'Sortie'), ('rendue', 'Rendue')], default='sortie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.department')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to='orders.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
