# Generated by Django 6.0.7 on 2026-08-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_bon_bonitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bon',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bon',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('valide', 'Valide'), ('annule', 'Annule')], default='actif', max_length=20),
        ),
    ]
