# Generated by Django 6.0.7 on 2026-08-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_bon_validated_at_bon_validated_by_alter_bon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('achat', 'Achat'), ('approvisionnement', 'Approvisionnement'), ('avoir', 'Avoir'), ('consignation', 'Consignation'), ('deconsignation', 'Deconsignation'), ('facturation', 'Facturation'), ('annulation_facture', 'Retour annulation de facture'), ('sortie_vente', 'Sortie vente'), ('transfert', 'Transfert'), ('sortie_caisse', 'Sortie de caisse'), ('avaries', 'Avaries'), ('octroi_budget', 'Octroi de budget approvisionneur'), ('fond_caisse', 'Fond de caisse (ouverture de journee)')], max_length=40),
        ),
    ]
