# Generated by Django 6.0.7 on 2026-09-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('achat', 'Achat'), ('approvisionnement', 'Approvisionnement'), ('avoir', 'Avoir'), ('consignation', 'Consignation'), ('deconsignation', 'Deconsignation'), ('facturation', 'Facturation'), ('annulation_facture', 'Retour annulation de facture'), ('sortie_vente', 'Sortie vente'), ('transfert', 'Transfert'), ('sortie_caisse', 'Sortie de caisse'), ('avaries', 'Avaries'), ('octroi_budget', 'Octroi de budget approvisionneur'), ('fond_caisse', 'Fond de caisse (ouverture de journee)'), ('ouverture_session', 'Ouverture de session de caisse'), ('fermeture_session', 'Fermeture de session de caisse')], max_length=40),
        ),
    ]
