# Generated by Django 6.0.7 on 2026-09-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_transaction_transaction_type'),
        ('organisations', '0012_cashierdaybalance_adjusted_after_close_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashexpense',
            name='cashier_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_expenses', to='organisations.cashierdaybalance'),
        ),
        migrations.AddField(
            model_name='cashexpense',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienttab',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cashier_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='organisations.cashierdaybalance'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
