# Generated by Django 5.2.3 on 2025-06-20 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_rename_phone_organisation_phone_contact_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_threshold',
            field=models.PositiveIntegerField(default=5, help_text="Seuil d'alerte de stock"),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pièce', max_length=20),
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.CharField(max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
