# Generated by Django 6.0.7 on 2026-07-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_departmentfamily'),
        ('products', '0003_product_code_product_purchase_price_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstock',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='organisations.departmentfamily'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='organisations.departmentfamily'),
        ),
    ]
