# Generated by Django 6.0.7 on 2026-07-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_departmentstock_family_stockmovement_family'),
    ]

    operations = [
        migrations.RunSQL(
            sql='UPDATE products_departmentstock SET family_id = NULL;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='UPDATE products_stockmovement SET family_id = NULL;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='departmentstock',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='products.category'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.category'),
        ),
    ]
