# Generated by Django 6.0.7 on 2026-09-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_budgetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shared_stock',
            field=models.BooleanField(default=False),
        ),
    ]
