# Generated by Django 6.0.7 on 2026-09-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_organisation_archivee_and_more'),
        ('products', '0009_product_shared_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='organisations.department'),
        ),
    ]
